### ISSUE TITLE
Port SIT.Manager.Updater

### ISSUE THREAD

**Issue by artehe** [Plootie/SIT.Manager.Avalonia#27]
I imagine you hadn't forgotten about this, but putting it in so that I don't.

Will need the accompanying features in the manager as well.

**Comment by Plootie** [comment]
I have thought about this a few times while working on this. I had actually made [this pull request](https://github.com/stayintarkov/SIT.Manager/pull/15) to overhaul the old managers updater just prior to starting work on this and so minimal changes will likely be needed. I was planning on waiting for us to finish up on the main manager to get an idea of what the published folder output would look like to ensure i know what kind of file structure we're looking at before implementing the updater
